return { }
--   {
--     'vhyrro/luarocks.nvim',
--     priority = 1000,
--     config = true
--   },
--   {
--     "nvim-neorg/neorg",
--     lazy = false,
--     version = '*',
--     config = function()
--       require("neorg").setup({
--         load = {
--           ["core.defaults"] = {},
--           ["core.dirman"] = {
--             config = {
--               workspaces = {
--                 notes = "~/notes"
--               },
--               default_workspace = "notes"
--             }
--           },
--           ["core.concealer"] = {},
--           ["core.completion"] = {
--             config = {
--               engine = "nvim-cmp"
--             }
--           },
--           ["core.export"] = {}
--         }
--       })
--     end
--   }
--
